### ISSUE TITLE
Add ability to show multiple channels when expanded

### ISSUE THREAD

**Issue by singulatarian** [singulatarian/gpt-scratchpad#13]
Also add a max-width for larger screens, otherwise it becomes hard to read as the content is too wide:
![image](https://github.com/singulatarian/gpt-scratchpad/assets/154478213/bcb2a59d-d86b-4a15-8315-641938d1bea7)

# Tasks
- [ ] Add max-width for messages
- [ ] When above a certain size, show other tabs
- [ ] Add ability to show multiple channels at once
- [ ] Add shortcut to switch between channels
